### ISSUE TITLE
Copyright text for mentioning your work in a project

### ISSUE THREAD

**Issue by mikepdiy** [danionescu0/arduino#2]
Hi Dan, 

Awesome work with the USB project hack. 
I am using part of the code in a project that will become commercial but opensource and I would like to credit you for the amazing work you have provided for the community but there is no text in the code that would mention any wish for persistence. Is there anything that I should add in the code or just mention your github page ?

**Comment by danionescu0** [comment]
Hi there

It will be great if you could mention my github project page, thanks. Can i ask what project are you working on ?

**Comment by mikepdiy** [comment]
Sigur :-) . Un macro keyboard putin mai evoluat fata de cele pe piata . Daca vrei putem discuta mai mult pe mail.
Just in case anyone else will read this aside from me and Dan, the project that I am working on is a macro keyboard with a twist on the functionality .

**Comment by danionescu0** [comment]
Sounds interesting, add me on Linkedin and we'll talk there (it's on  my github profile page)

**Comment by mikepdiy** [comment]
Sure thing. I will close this issue now as it is clear the response from you :-)
